"""Public API for the single production JMR graph."""

from .full import FullGraphState, build_graph, compile_graph, create_initial_state
from .identity import (
    InvocationIdentity,
    InvocationIdentityError,
    validate_invocation_identity,
)
from .manifest import (
    LEGAL_STAGE_TRANSITIONS,
    NODE_MANIFEST,
    NodeKind,
    NodeSpec,
    agent_tools_for,
    can_transition,
    nodes_for_stage,
)
from .state import (
    GRAPH_STATE_SCHEMA_VERSION,
    MAX_GRAPH_MESSAGE_BYTES,
    MAX_GRAPH_MESSAGES,
    MAX_GRAPH_MESSAGES_BYTES,
    InterruptDescriptor,
    JMRGraphState,
    RetrievalRef,
    create_jmr_graph_state,
    deserialize_jmr_graph_state,
    keep_immutable_identifier,
    merge_retrieval_refs,
    merge_unique_strings,
    messages_as_dicts,
    normalize_jmr_graph_state,
    normalize_messages,
    serialize_jmr_graph_state,
)

__all__ = [
    "GRAPH_STATE_SCHEMA_VERSION",
    "LEGAL_STAGE_TRANSITIONS",
    "MAX_GRAPH_MESSAGES",
    "MAX_GRAPH_MESSAGES_BYTES",
    "MAX_GRAPH_MESSAGE_BYTES",
    "NODE_MANIFEST",
    "FullGraphState",
    "InterruptDescriptor",
    "InvocationIdentity",
    "InvocationIdentityError",
    "JMRGraphState",
    "NodeKind",
    "NodeSpec",
    "RetrievalRef",
    "agent_tools_for",
    "build_graph",
    "can_transition",
    "compile_graph",
    "create_initial_state",
    "create_jmr_graph_state",
    "deserialize_jmr_graph_state",
    "keep_immutable_identifier",
    "merge_retrieval_refs",
    "merge_unique_strings",
    "messages_as_dicts",
    "nodes_for_stage",
    "normalize_jmr_graph_state",
    "normalize_messages",
    "serialize_jmr_graph_state",
    "validate_invocation_identity",
]
